apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: release-engineer
rules:
  - apiGroups: [""]
    resources: ["nodes", "namespaces", "pods", "services"]
    verbs: ["get", "list"]
  - apiGroups: ["apps"]
    resources: ["deployments" ,"daemonsets" ,"statefulsets" ,"replicasets"]
    verbs: ["get", "list", "create"]
  - apiGroups: [ "batch"]
    resources: ["jobs", "cronjobs"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: release-engineer
subjects:
  - kind: User
    name: eks-release-engineer
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: release-engineer
  apiGroup: rbac.authorization.k8s.io
