apiVersion: v1
kind: Service
metadata:
  labels:
    app: myapp
  name: myapp-np
spec:
  type: NodePort
  selector:
    app: myapp
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
    nodePort: 30001